### ISSUE TITLE
Test for Python 3.9, drop support for Python 3.5?

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/SurfaceTopography#41]
Now Python 3.9 is out:

https://pythoninsider.blogspot.com/2020/10/python-390-is-now-available-and-you-can.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29

Python 3.5 is no longer supported. Currently the tests in CI run for Python 3.5, 3.6, 3.7, 3.8. 
Shall we also drop support for Python 3.5 and test for Python 3.9 instead?

**Comment by pastewka** [comment]
Yes, let's drop support for Python 3.5. We have also dropped support in https://github.com/libAtoms/matscipy recently. This would allow us to use f-strings.
