### ISSUE TITLE
Filters do not follow the pipeline model

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/SurfaceTopography#45]
The current implementation of the filters creates a new topography object that contains the filtered data. This does not conform to the pipeline model, that should filter the data on the fly.

**Comment by AntoineSIMTEK** [comment]
You mean that it should apply the filter on the original data (contained in ._height) at each call to .height() correct ? Then the current behaviour of .height() would correspond to .height().squeeze() in the correct implementation of the pipeline model.

**Comment by pastewka** [comment]
Exactly, that is what I mean.

**Comment by pastewka** [comment]
The evaluation of the pipeline is lazy, not immediate.

**Comment by AntoineSIMTEK** [comment]
Ok I will do these changes.

**Comment by AntoineSIMTEK** [comment]
We should probably write a paragraph in the doc on the pipeline concept.

**Comment by pastewka** [comment]
Thanks!

**Comment by pastewka** [comment]
Yes

**Comment by AntoineSIMTEK** [comment]
What does "Pipelines can be concatenated together." mean in usage.rst -> Pipelines ?

**Comment by pastewka** [comment]
Well... pipelines can be extended would probably be better.

**Comment by AntoineSIMTEK** [comment]
or chained ?

**Comment by pastewka** [comment]
Something like this...

**Comment by AntoineSIMTEK** [comment]
Ok will implement a suggestion. And will but a concrete example just below. Then it's clear.

**Comment by pastewka** [comment]
Has this been resolved @AntoineSIMTEK ?

**Comment by AntoineSIMTEK** [comment]
I think I did it. See for example bf1aa06c. I lost the habit of tagging the issue in the commits. 
I suggest to reopen if a missed some functions.
