### ISSUE TITLE
Empty subdomain errors in parallel tests with muFFT==0.12.0

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ComputationalMechanics/SurfaceTopography#47]
in test/test_make_sphere.py: 

>       engine = factory(nb_grid_pts, communicator, **kwargs)
E       RuntimeError: Invalid nb_subdomain_grid_pts (=(8, 0)) passed during initialisation.
E       Traceback from C++ library (most recent call last):

See e.g.:
https://travis-ci.org/github/ComputationalMechanics/SurfaceTopography/jobs/745051709

By looking at the subdomain slices in the older version, I noted there was already a processor holding empty subdomain. 

@pastewka  I guess you introduced a warning for the empty subdomains and that is good. 

I will increase the number of points in the test. That should solve the problem.

**Comment by pastewka** [comment]
This is a bug. muFFT should gracefully allow for empty CPUs, because this is something that happens in reality with FFTW. I will check what is going on on the muFFT side.

This does not seems to be a problem with FFTW, but with the underlying field collections.

**Comment by pastewka** [comment]
Do you what grid and how many CPUs caused this problem? I would like to add a test on the muFFT side for this.

**Comment by AntoineSIMTEK** [comment]
4 CPUs nx 8 ny 5 for exampleSent from Android deviceOn 23 Nov 2020 17:03, Lars Pastewka <notifications@github.com> wrote:
Do you what grid and how many CPUs caused this problem? I would like to add a test on the muFFT side for this.

**Comment by pastewka** [comment]
Okay, thanks.
