### ISSUE TITLE
Current NETCDF  default not readable with MATLAB

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ComputationalMechanics/SurfaceTopography#48]
https://github.com/ComputationalMechanics/SurfaceTopography/blob/6412061c9b59759606592359bd3111721de19558/SurfaceTopography/IO/NC.py#L181

Current default format='NETCDF3_64BIT_DATA' was not readable with @lthimons MATLAB installation on windows. 

'NETCDF4' worked (by the way this is the default according to the docstring).

''
We tested with only one MATLAB installation however, the current default 'NETCDF3_64BIT_DATA' is not listed here:
https://www.mathworks.com/help/matlab/ref/netcdf.inqformat.html#bs6plhe_seealso

**Comment by pastewka** [comment]
Does NETCDF3_64BIT_OFFSET work?


________________________________
Von: Antoine Sanner <notifications@github.com>
Gesendet: Sonntag, 29. November 2020 08:42
An: ComputationalMechanics/SurfaceTopography
Cc: Lars Pastewka; Assign
Betreff: [ComputationalMechanics/SurfaceTopography] Current NETCDF default not readable with MATLAB (#48)

**Comment by pastewka** [comment]
64BIT_DATA is only supported in recent version of NetCDF, I think starting with 3.6
